---
title: SortingHat custom settings for BAP
category: fixed
author: Jose Javier Merchante <jjmerchante@bitergia.com>
issue: null
notes: >
  Create a custom settings file for BAP images that uses
  `sortinghat.config.settings` as default and includes
  custom configuration for BAP. The new file is available as
  `sortinghat.config.settings_bap`.
